services:
  db:
    image: postgres:16-alpine
    container_name: prova-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    image: emanuelbap/social-post-api:latest
    container_name: prova-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      USERS_API_URL: ${USERS_API_URL}
      USERS_API_TIMEOUT: ${USERS_API_TIMEOUT}
    depends_on:
      - db
    ports:
      - "80:8000"
    restart: always

volumes:
  pgdata: